sudo: required
services:
  - docker

before_install:
  - docker build -t martabs/testing-cd -f Dockerfile.dev .

script:
  - docker run martabs/testing-cd npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "testing-cd"
  env: "TestingCd-env"
  bucket_name: "elasticbeanstalk-us-east-2-8026358393460"
  bucket_path: "testing-cd"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"